# This is a basic workflow to help you get started with Actions

name: Deploy frontend to blob store

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main

##permissions:
##  id-token: write
##  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 'Az CLI Login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Upload to blob storage
      uses: Azure/cli@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name resume23sa --auth-mode key --destination '$web' --source . --overwrite
    
    - name: Copy function code files
      uses: Azure/cli@v1
      with:
        inlineScript: |
          az storage file upload --account-name resume23sa --share-name AzureResume-func --source ./backend/run.ps1 --path "site/wwwroot/VisitorCounter"
          az storage file upload --account-name resume23sa --share-name AzureResume-func --source ./backend/function.json --path "site/wwwroot/VisitorCounter"
    
    - name: Purge CDN endpoint
      uses: Azure/cli@v1
      with:
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "azureresume-cdnp" --name "cdne-salman-cv-uk" --resource-group "resume-cli-rg" --no-wait
    
    - name: logout
      run: |
        az logout
